name: Quick Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quick-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn pydantic pytest

    - name: Simple Python test
      run: |
        python -c "print('✅ Python environment is working')"
        python -c "import pandas; print(f'✅ pandas {pandas.__version__}')"
        python -c "import numpy; print(f'✅ numpy {numpy.__version__}')"
        python -c "import sklearn; print(f'✅ sklearn {sklearn.__version__}')"

    - name: Check file structure
      run: |
        echo "Checking project structure..."
        if [ -f "requirements.txt" ]; then
          echo "✅ requirements.txt exists"
        else
          echo "⚠️ requirements.txt not found"
        fi
        
        if [ -f "src/api/app.py" ]; then
          echo "✅ src/api/app.py exists"
        else
          echo "⚠️ src/api/app.py not found"
        fi

    - name: Final success
      run: |
        echo "✅ All quick tests passed!"
        echo "🚀 Project is ready for development"